services:
  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx_logs:/var/log/nginx
    network_mode: host
    ports:
      - "0.0.0.0:80:80"
    tmpfs:
      - /var/run/fail2ban/
    depends_on:
      - backend
  failtoban:
    build:
      context: .
      dockerfile: failtoban/Dockerfile
    volumes:
      - ./nginx_logs:/var/log/nginx
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - frontend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "3000"
      - "7777-7786:7777-7786/udp"
      - "7777-7786:7777-7786/tcp"
    network_mode: host
    env_file:
      - prod.env
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - TZ=UTC
    env_file:
      - portainer.env

volumes:
  portainer_data:
    driver: local
