services:
  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - 3000
    env_file:
      - prod.env
