services:
  # Nginx adds SSL
  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    network_mode: host
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - nginx_logs:/var/log/nginx/
    depends_on:
      - backend
  # I'm a bit of exhausted of scammer scanning
  failtoban:
    build:
      context: .
      dockerfile: failtoban/Dockerfile
    restart: always
    volumes:
      - nginx_logs:/var/log/nginx/
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - frontend
  # Backend handles requests
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    network_mode: host
    expose:
      - "3000"
    env_file:
      - prod.env
    depends_on:
      - redis_db
  # Redis as KVS for matchmaking logic
  redis_db:
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - redis.env
    ports:
      - "0.0.0.0:6379:6379"
  # Postgres as persistent storage
  postgres_db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - postgres.env
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # Portainer is used for monitoring containers through Web interface
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: --admin-password '$$2b$$12$$eTpQT9G0sVpiuXS95w9PsehIybqSUC2QuzQXsrelI9Nae.d.bSZ0O'
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - TZ=UTC


volumes:
  portainer_data:
    driver: local
  nginx_logs:
    driver: local
  postgres_data:
    driver: local
